baseURL = 'https://dylanreed.com/'
languageCode = 'en-us'
title = 'Dylan Reed'

[params]
  name = "Dylan Reed"
  headline = "Creative coder | Puppet wrangler | Animation anarchist"
  image = "https://www.gravatar.com/avatar/36aff981378cc0b408b7d1bc2f082741?s=240&d=mp"

[[params.links]]
  name = "Contact"
  url = "/contact/"
  icon = "email"

[[params.links]]
  name = "Blog"
  url = "https://dylan.blog"
  icon = "blog"

[[params.links]]
  name = "GitHub"
  url = "https://github.com/dylanreed"
  icon = "github"

[[params.links]]
  name = "OpenSea"
  url = "https://opensea.io/dylanreed.eth"
  icon = "opensea"

[[params.links]]
  name = "Instagram"
  url = "https://instagram.com/dylanreed"
  icon = "instagram"

[[params.links]]
  name = "LinkedIn"
  url = "https://www.linkedin.com/in/dylannotdylan/"
  icon = "linkedin"

[[params.links]]
  name = "About"
  url = "https://dylan.blog/who-is/"
  icon = "about"
