baseURL = 'http://dylanreed.com/'
languageCode = 'en-us'
title = 'Dylan Reed'


[author]
  name = "Dylan Reed"
  headline = "ğŸ­ Dylan Reed Creative coder | Puppet wrangler | Animation anarchist ğŸ§µ I build scripts that talk, blink, and misbehave ğŸ‘ï¸â€ğŸ—¨ï¸ 1940s cartoons meet 2040s AI ğŸ§° Python, Pygame, FFMPEG, vintage vibes ğŸ¤ Ask me about visemes, yarn crimes, or cyber-comedy
  image = "https://www.gravatar.com/avatar/36aff981378cc0b408b7d1bc2f082741?s=240&d=mp"
  links = [

    { email =  { href = "contact", text = "Contact me", target = "_self" } },
    { link = { href = "https://dylan.blog", text = "My blog" } },
    { github = "https://github.com/dylanreed" },
    { ethereum = { href = "https://etherscan.io/enslookup-search?search=dylanreed.eth", text = "dylanreed.eth", target = "_self" } },
    { opensea = { href = "https://opensea.io/dylanreed.eth", text = "OpenSea", target = "_self" } },
    
    { instagram = "https://instagram.com/dylanreed" },
    { linkedin = "https://www.linkedin.com/in/dylannotdylan/" },
    { page = { href = "about", text = "About", target = "_self" } },
  ]
